export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SNIPPETS = 'SNIPPETS';
export const NEW_SNIPPET = 'NEW_SNIPPET';
export const REMOVE_SNIPPET = 'REMOVE_SNIPPET';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CLEAR_CACHE = 'CLEAR_CACHE';
export const SET_COURSES = 'SET_COURSES';
export const CLEAR_COURSES = 'CLEAR_COURSES';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';

export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE';
export const UPDATE_DARK_MODE = 'UPDATE_DARK_MODE';
export const UPDATE_CONTEXT_AMOUNT = 'UPDATE_CONTEXT_AMOUNT';
export const UPDATE_CHAR_COLUMN = 'UPDATE_CHAR_COLUMN';
export const UPDATE_CHAR_COLUMN_OFFSET = 'UPDATE_CHAR_COLUMN_OFFSET';
