"""Make it possible to delete submissions with comments

Revision ID: 0cfce1799c57
Revises: 3b8c7d61ece8
Create Date: 2017-09-22 22:42:41.033066

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0cfce1799c57'
down_revision = '3b8c7d61ece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Comment_File_id_fkey', 'Comment', type_='foreignkey')
    op.drop_constraint('Comment_User_id_fkey', 'Comment', type_='foreignkey')
    op.create_foreign_key('Comment_User_id_fkey', 'Comment', 'User', ['User_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('Comment_File_id_fkey', 'Comment', 'File', ['File_id'], ['id'], ondelete='CASCADE')

    op.drop_index('ix_LinterComment_File_id', table_name='LinterComment')
    op.drop_constraint('LinterComment_File_id_fkey', 'LinterComment', type_='foreignkey')
    op.create_index(op.f('ix_LinterComment_File_id'), 'LinterComment', ['File_id'], unique=False)
    op.create_foreign_key('LinterComment_File_id_fkey', 'LinterComment', 'File', ['File_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('LinterInstance_Work_id_fkey', 'LinterInstance', type_='foreignkey')
    op.create_foreign_key('LinterInstance_Work_id_fkey', 'LinterInstance', 'Work', ['Work_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LinterComment_File_id'), table_name='LinterComment')
    op.drop_constraint('LinterComment_File_id_fkey', 'LinterComment', type_='foreignkey')
    op.create_foreign_key('LinterComment_File_id_fkey', 'LinterComment', 'File', ['File_id'], ['id'])
    op.create_index('ix_LinterComment_File_id', 'LinterComment', ['File_id'], unique=False)

    op.drop_constraint('Comment_File_id_fkey', 'Comment', type_='foreignkey')
    op.drop_constraint('Comment_User_id_fkey', 'Comment', type_='foreignkey')
    op.create_foreign_key('Comment_User_id_fkey', 'Comment', 'User', ['User_id'], ['id'])
    op.create_foreign_key('Comment_File_id_fkey', 'Comment', 'File', ['File_id'], ['id'])

    op.drop_constraint('LinterInstance_Work_id_fkey', 'LinterInstance', type_='foreignkey')
    op.create_foreign_key('LinterInstance_Work_id_fkey', 'LinterInstance', 'Work', ['Work_id'], ['id'])
    # ### end Alembic commands ###
