"""Add `reset_email_on_lti` column

Revision ID: 10ad986794e4
Revises: 93f2e429654d
Create Date: 2018-01-18 23:38:41.759503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ad986794e4'
down_revision = '93f2e429654d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('reset_email_on_lti', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'reset_email_on_lti')
    # ### end Alembic commands ###
