"""empty message

Revision ID: 150b205df625
Revises: 480d173bf43f
Create Date: 2017-08-24 18:51:47.161327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150b205df625'
down_revision = '480d173bf43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.Unicode(), nullable=False))
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.drop_constraint('User_email_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_email_key', 'User', ['email'])
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
