"""empty message

Revision ID: 4d3531723478
Revises: f8f4ecfd1e2b
Create Date: 2017-09-02 00:03:35.174225

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d3531723478'
down_revision = 'f8f4ecfd1e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('File_Work_id_fkey', 'File', type_='foreignkey')
    op.create_foreign_key('File_Work_id_fkey', 'File', 'Work', ['Work_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('File_Work_id_fkey', 'File', type_='foreignkey')
    op.create_foreign_key('File_Work_id_fkey', 'File', 'Work', ['Work_id'], ['id'])
    # ### end Alembic commands ###
