"""Add AssignmentAssignedGrader table

Revision ID: 56c9dc73440a
Revises: 3b8c7d61ece8
Create Date: 2017-09-25 17:21:00.746484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c9dc73440a'
down_revision = '3b8c7d61ece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssignmentAssignedGrader',
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('User_id', sa.Integer(), nullable=False),
                    sa.Column('Assignment_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['Assignment_id'], ['Assignment.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('Assignment_id', 'User_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LinterComment_File_id'), table_name='LinterComment')
    op.drop_table('AssignmentAssignedGrader')
    # ### end Alembic commands ###
