"""empty message

Revision ID: 57167e5c868a
Revises: 6b72d26d1ab0
Create Date: 2017-08-28 13:42:36.019922

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '57167e5c868a'
down_revision = '6b72d26d1ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RubricItem', sa.Column('header', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RubricItem', 'header')
    # ### end Alembic commands ###
