"""Add reset_token column

Revision ID: 5fce393529d2
Revises: abcddf37ebfa
Create Date: 2017-09-11 18:52:17.494441

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5fce393529d2'
down_revision = 'abcddf37ebfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('reset_token', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'reset_token')
    # ### end Alembic commands ###
