"""empty message

Revision ID: 6b72d26d1ab0
Revises: 150b205df625
Create Date: 2017-08-27 17:22:24.021598

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6b72d26d1ab0'
down_revision = '150b205df625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GradeHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('is_rubric', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('passed_back', sa.Boolean(), nullable=True),
    sa.Column('Work_id', sa.Integer(), nullable=True),
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Work_id'], ['Work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GradeHistory')
    # ### end Alembic commands ###
