"""Rename 'can_update_grading' reminder to 'can_update_course_notification'

Revision ID: 7b03e3da9996
Revises: e7a1ef67ec03
Create Date: 2018-01-22 01:08:58.671580

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '7b03e3da9996'
down_revision = 'e7a1ef67ec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(text("""
    UPDATE "Permission"
    SET name = 'can_update_course_notifications'
    WHERE name = 'can_update_grading_reminder'
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(text("""
    UPDATE "Permission"
    SET name = 'can_update_grading_reminder'
    WHERE name = 'can_update_course_notifications'
    """))
    # ### end Alembic commands ###
