"""Add `can_search_users` permission

Revision ID: 998d96ca2c36
Revises: ddb38c4abccc
Create Date: 2017-12-28 06:00:00.536722

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '998d96ca2c36'
down_revision = 'ddb38c4abccc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text("""
    INSERT INTO "Permission" (name, default_value, course_permission)
    SELECT 'can_search_users', true, false WHERE NOT EXISTS
        (SELECT 1 FROM "Permission" WHERE name = 'can_search_users')
    """))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
