"""Add short_desc & long_desc columns to Permission table

Revision ID: a4c339dd2b85
Revises: ddb38c4abccc
Create Date: 2017-11-30 14:00:05.808241

"""
from alembic import op
import sqlalchemy as sa

import json
import os


# revision identifiers, used by Alembic.
revision = 'a4c339dd2b85'
down_revision = 'ddb38c4abccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Permission', sa.Column('long_desc', sa.Unicode(), nullable=True))
    op.add_column('Permission', sa.Column('short_desc', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###

    t_perms = sa.Table(
        'Permission',
        sa.MetaData(),
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.Unicode),
        sa.Column('short_desc', sa.Unicode),
        sa.Column('long_desc', sa.Unicode),
    )
    conn = op.get_bind()

    with open(
        f'{os.path.dirname(os.path.abspath(__file__))}/../../seed_data/permissions.json',
        'r'
    ) as perms:
        perms = json.load(perms)
        for name, perm in perms.items():
            conn.execute(t_perms.update().where(t_perms.c.name == name).values(
                short_desc=perm['short_description'],
                long_desc=perm['long_description'],
            ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Permission', 'short_desc')
    op.drop_column('Permission', 'long_desc')
    # ### end Alembic commands ###
