"""Add the 'can_edit_own_password' permission

Revision ID: abcddf37ebfa
Revises: 1b14f6bef6a1
Create Date: 2017-09-09 01:00:48.004082

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = 'abcddf37ebfa'
down_revision = '1b14f6bef6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text("""
    INSERT INTO "Permission" (name, default_value, course_permission)
    SELECT 'can_edit_own_password', true, false WHERE NOT EXISTS
        (SELECT 1 FROM "Permission" WHERE name = 'can_edit_own_password')
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
