"""Add CGIgnore column to assignment

Revision ID: ddb38c4abccc
Revises: 8fed7758b6b2
Create Date: 2017-10-05 17:45:10.600492

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ddb38c4abccc'
down_revision = '8fed7758b6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('cgignore', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Assignment', 'cgignore')
    # ### end Alembic commands ###
