"""Change the fields used for reminders

Revision ID: e7a1ef67ec03
Revises: 93f2e429654d
Create Date: 2018-01-18 01:04:43.007426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7a1ef67ec03'
down_revision = '93f2e429654d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('done_email', sa.Unicode(), nullable=True))
    enum = sa.Enum('assigned_only', 'all_graders', name='assignmentdonetype')
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column('Assignment', sa.Column('done_type', enum, nullable=True))
    op.drop_column('Assignment', 'reminder_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Assignment', sa.Column('reminder_type', postgresql.ENUM('none', 'assigned_only', 'all_graders', name='assignmentremindertype'), server_default=sa.text("'none'::assignmentremindertype"), autoincrement=False, nullable=False))
    op.drop_column('Assignment', 'done_type')
    op.drop_column('Assignment', 'done_email')
    # ### end Alembic commands ###
