"""empty message

Revision ID: f8f4ecfd1e2b
Revises: 57167e5c868a
Create Date: 2017-08-31 15:57:26.533979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f8f4ecfd1e2b'
down_revision = '57167e5c868a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RubricRow', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RubricRow', 'created_at')
    # ### end Alembic commands ###
