#!/bin/bash

res="127"

echo "Running test with pwd: $(pwd)"

set -o xtrace

if [[ "$TO_RUN" = "postgres-test" ]]; then
    TEST_FLAGS="--postgresql=travis_ci_test"
    SQLALCHEMY_DATABASE_URI='postgresql:///travis_ci_test' ./manage.py db upgrade
fi

case "$TO_RUN" in
    "coverage")
        pytest --cov psef --cov-report term-missing "$(pwd)/psef_test/" -vvvv
        res="$?"
        set +o xtrace
        ;;
    "tests"|"postgres-test")
        pytest -vvvv $TEST_FLAGS "$(pwd)/psef_test/"
        res="$?"
        if [[ "$res" -eq 0 ]]; then
            cd docs || exit 1
            make html
            res="$?"
        fi
        set +o xtrace
        ;;
    "mypy")
        mypy --ignore-missing-imports --disallow-untyped-defs --check-untyped-defs --disallow-subclassing-any "$(pwd)/psef/"
        res="$?"
        set +o xtrace
        ;;
    "lint")
        flake8 "$(pwd)/psef/"
        res="$?"
        make privacy_statement
        [[ -z "$NO_INSTALL" ]] && npm install
        if ! npm run lint; then
            res="1"
        fi
        set +x xtrace
        ;;
    "yapf")
        out="$(yapf -rdp "$(pwd)/psef" "$(pwd)/psef_test")"
        set +o xtrace
        if [[ "$out" ]]; then
            echo "$out"
            res=1
        else
            res=0
        fi
        ;;

esac

set +o xtrace

exit "$res"
